gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>F1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>F2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>F3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>F4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>F5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>F6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>F7']"
